# Generated by Django 2.2.2 on 2019-06-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='next_post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='previous_post',
        ),
    ]
